version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - PORT=8080
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:8080}